version: '3.4'

services:
  db:
    image: rest-with-aspnet-bd-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_asp_net
    ports:
      - 3308:3306
    networks:
      - rest-aspnet-network
      
  rest-with-aspnet-bd:
    image: rest-with-aspnet-bd
    build:
      context: .
      dockerfile: RESTWithASPNETBD/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 7150:80
    depends_on:
      - db
    networks:
      - rest-aspnet-network

networks:
  rest-aspnet-network:
    driver: bridge
    
    
      
    
